import { Doll } from "../ts/types";
export const data: Array<Doll> = [
  {
    id: 1,
    name: "Antique beautiful rare doll",
    rare: true,
    brand: "Other",
    year: 1920,
    type: "antique",
    outfit: "full",
    hight: 43,
    img: "../img/dolls/1.jpg",
  },
  {
    id: 2,
    name: "Little miss sadness",
    rare: true,
    brand: "Other",
    year: 1965,
    type: "antique",
    outfit: "full",
    hight: 35,
    img: "../img/dolls/2.jpg",
  },
  {
    id: 3,
    name: "Cutie Sad Eyes",
    rare: true,
    brand: "Other",
    year: 1974,
    type: "antique",
    outfit: "full",
    hight: 35,
    img: "../img/dolls/3.jpg",
  },
  {
    id: 4,
    name: "Totally Hair Barbie",
    rare: true,
    brand: "Barbie",
    year: 1991,
    type: "collection",
    outfit: "full",
    hight: 28,
    img: "../img/dolls/4.jpg",
  },
  {
    id: 5,
    name: "Happy Holidays Barbie",
    rare: true,
    brand: "Barbie",
    year: 1994,
    type: "play",
    outfit: "full",
    hight: 28,
    img: "../img/dolls/5.jpg",
  },
  {
    id: 6,
    name: "Barbie Black Label",
    rare: false,
    brand: "Barbie",
    year: 2003,
    type: "collection",
    outfit: "full",
    hight: 28,
    img: "../img/dolls/6.jpg",
  },
  {
    id: 7,
    name: "Barbie Fashionistas",
    rare: false,
    brand: "Barbie",
    year: 2022,
    type: "play",
    outfit: "full",
    hight: 28,
    img: "../img/dolls/7.jpg",
  },
  {
    id: 8,
    name: "Barbie Britan's Queen",
    rare: true,
    brand: "Barbie",
    year: 2022,
    type: "collection",
    outfit: "full",
    hight: 28,
    img: "../img/dolls/8.jpg",
  },
  {
    id: 9,
    name: "Cinderella",
    rare: true,
    brand: "Other",
    year: 2015,
    type: "BJD",
    outfit: "wig and makeup",
    hight: 45,
    img: "../img/dolls/9.jpg",
  },
  {
    id: 10,
    name: "East Princess",
    rare: true,
    brand: "Other",
    year: 2019,
    type: "BJD",
    outfit: "wig and makeup",
    hight: 45,
    img: "../img/dolls/10.jpg",
  },
  {
    id: 11,
    name: "Taeyang",
    rare: false,
    brand: "Pullip",
    year: 2010,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/11.jpg",
  },
  {
    id: 12,
    name: "Gothic Baby Blythe",
    rare: true,
    brand: "Blythe",
    year: 2010,
    type: "OOAK",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/12.jpg",
  },
  {
    id: 13,
    name: "Funny Blythe",
    rare: true,
    brand: "Blythe",
    year: 2021,
    type: "OOAK",
    outfit: "only makeup",
    hight: 30,
    img: "../img/dolls/13.jpg",
  },
  {
    id: 14,
    name: "Blythe in a hat",
    rare: false,
    brand: "Blythe",
    year: 2022,
    type: "play",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/14.jpg",
  },
  {
    id: 15,
    name: "Modern Blythe",
    rare: true,
    brand: "Blythe",
    year: 2022,
    type: "OOAK",
    outfit: "wig and makeup",
    hight: 30,
    img: "../img/dolls/15.jpg",
  },
  {
    id: 16,
    name: "Bonnie",
    rare: false,
    brand: "Iplehouse",
    year: 2018,
    type: "BJD",
    outfit: "only makeup",
    hight: 45,
    img: "../img/dolls/16.jpg",
  },
  {
    id: 17,
    name: "Isabel",
    rare: false,
    brand: "Iplehouse",
    year: 2020,
    type: "BJD",
    outfit: "none",
    hight: 60,
    img: "../img/dolls/17.jpg",
  },
  {
    id: 18,
    name: "Mari",
    rare: true,
    brand: "Iplehouse",
    year: 2022,
    type: "BJD",
    outfit: "full",
    hight: 60,
    img: "../img/dolls/18.jpg",
  },
  {
    id: 19,
    name: "Linda",
    rare: false,
    brand: "Iplehouse",
    year: 2017,
    type: "BJD",
    outfit: "only makeup",
    hight: 45,
    img: "../img/dolls/19.jpg",
  },
  {
    id: 20,
    name: "Yshtola",
    rare: true,
    brand: "Other",
    year: 2021,
    type: "BJD",
    outfit: "full",
    hight: 35,
    img: "../img/dolls/20.jpg",
  },
  {
    id: 21,
    name: "Queen of hearts Pullip",
    rare: true,
    brand: "Pullip",
    year: 2010,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/21.jpg",
  },
  {
    id: 22,
    name: "Pullip in Red",
    rare: false,
    brand: "Pullip",
    year: 2011,
    type: "play",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/22.jpg",
  },
  {
    id: 23,
    name: "Alice Pullip",
    rare: true,
    brand: "Pullip",
    year: 2013,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/23.jpg",
  },
  {
    id: 24,
    name: "Day of the Dead Barbie",
    rare: true,
    brand: "Barbie",
    year: 2021,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/24.jpg",
  },
  {
    id: 25,
    name: "Ballet Dancer Barbie",
    rare: false,
    brand: "Barbie",
    year: 2022,
    type: "play",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/25.jpg",
  },
  {
    id: 26,
    name: "Steampunk Blythe",
    rare: true,
    brand: "Blythe",
    year: 2012,
    type: "OOAK",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/26.jpg",
  },
  {
    id: 27,
    name: "Blythe with the Red Bow",
    rare: false,
    brand: "Blythe",
    year: 2021,
    type: "play",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/27.jpg",
  },
  {
    id: 28,
    name: "Lynn",
    rare: false,
    brand: "Iplehouse",
    year: 2010,
    type: "BJD",
    outfit: "none",
    hight: 45,
    img: "../img/dolls/28.jpg",
  },
  {
    id: 29,
    name: "Olivia",
    rare: true,
    brand: "Other",
    year: 2010,
    type: "BJD",
    outfit: "only makeup",
    hight: 40,
    img: "../img/dolls/29.jpg",
  },
  {
    id: 30,
    name: "White Kitten Pullip",
    rare: false,
    brand: "Pullip",
    year: 2014,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/30.jpg",
  },
  {
    id: 31,
    name: "Pocahontas Pullip",
    rare: false,
    brand: "Pullip",
    year: 2016,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/31.jpg",
  },
  {
    id: 32,
    name: "Steampunk Mad Hatter Pullip",
    rare: true,
    brand: "Pullip",
    year: 2021,
    type: "collection",
    outfit: "full",
    hight: 30,
    img: "../img/dolls/32.jpg",
  },
];
